[[customizations.user]]
name = "your-username"
password = "your-password"
groups = ["wheel"]

[customizations.installer.kickstart]
contents = """
ostreecontainer --url ghcr.io/sapmelonnnn/ublue-niri:latest --no-signature-verification
"""
