[[customizations.user]]
name = "live"
password = "1234"
groups = ["wheel"]

[customizations.installer.kickstart]
contents = """
ostreecontainer --url ghcr.io/sapmelonnnn/ublue-niri:latest --no-signature-verification
"""
